Added msgtansferresposne
AbstractSDK/cw-multi-test-fork pull request #10
Opened 2024-11-05 09:21 UTC by Kayanski

This PR aims at adding the msgTransferResponse when sending ICS20 tokens. 
This will be used for callbacks within abstract and this is a good thing to support here

2024-11-07 17:00 UTC, Buckram123 requested changes
That's awesome that we can use memo functionality in multi-test environment now, but I don't think it's right to assume every memo is a json and we shouldn't error if one of the fields is incorrectly structured

2024-11-07 17:00 UTC, Buckram123 commented on src/bank.rs
> +            let json: Value = serde_json::from_str(&memo)?;
```suggestion
            let json: serde_json::Result<Value> = serde_json::from_str(&memo);
```
We can't assume any memo is a json

2024-11-07 17:00 UTC, Buckram123 commented on src/bank.rs
> +                let msg = wasm["msg"].clone();
I would suggest you to create structure for deserialization, also it shouldn't error on invalid structure, but skip action instead

2024-11-07 17:00 UTC, Buckram123 commented on src/ibc/simple_ibc.rs
> +            let json: Value = serde_json::from_str(&packet.memo.unwrap_or("{}".to_string()))?;
We can't assume memo is a json here as well I think

2024-11-07 17:00 UTC, Buckram123 commented on src/bank.rs
> +}
Great!

2024-11-07 17:00 UTC, Buckram123 commented on src/bank.rs
> +        let contract_exec = if let Some(memo) = packet.memo {
Would it be possible to put into separate file? memo parsing could grow quite heavliy, depending on what we implement in the future

2024-11-11 09:51 UTC, Kayanski commented on src/bank.rs
> +                let msg = wasm["msg"].clone();
For the first, yes ! For the second however, the ibc hooks should error if there's a wasm attribute and the structure
--> https://github.com/cosmos/ibc-apps/blob/main/modules/ibc-hooks/README.md#ics20-packet-structure

2024-11-11 09:59 UTC, Buckram123 commented on src/bank.rs
> +                let msg = wasm["msg"].clone();
> For the first, yes ! For the second however, the ibc hooks should error if there's a wasm attribute and the structure --> https://github.com/cosmos/ibc-apps/blob/main/modules/ibc-hooks/README.md#ics20-packet-structure

Ah, nice. If we have "wasm" key we can freely error on invalid structure!

2024-11-11 10:15 UTC, Kayanski commented on src/bank.rs
> +        let contract_exec = if let Some(memo) = packet.memo {
Yes !

2024-11-12 10:24 UTC, Buckram123 reviewed
Nice additions

2024-11-12 10:24 UTC, Buckram123 commented on src/ibc/memo/callback.rs
> +}
Nice!

2024-11-12 10:24 UTC, Buckram123 commented on src/ibc/memo/ibc_hooks.rs
> +    println!("{:?}", packet.memo);
debug line, in case you missed it by accident

2024-11-18 13:41 UTC, merged